# Perfil Docker para solicitudes_service
# Configuración de MongoDB y Eureka para entorno Docker

server.port=8085

spring.data.mongodb.uri=mongodb://mongo-solicitudes:27017/solicitudes_service

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/