spring.application.name=solicitudes-service

server.port=8085

# Configuración de MongoDB local
spring.data.mongodb.uri=mongodb://localhost:27017/solicitudes_service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true