# Perfil Docker para empleado-service
# Sobreescribe las URLs de conexión para usar nombres de servicio Docker
server.port=8080

spring.datasource.url=jdbc:mysql://mysql-db:3306/empleado_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rootpassword

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
