spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          # Ubicación donde se encuentran los archivos .yml o .properties para los demás microservicios
          search-locations: classpath:/config

server:
  port: 8888

# Observabilidad: Configuración de endpoints de Actuator y métricas.
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
