# Nombre y puerto del servidor de descubrimiento (Eureka)
spring.application.name=discovery-server
server.port=8761

# Al ser el servidor (standalone mode), no debe registrarse a sí mismo
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Deshabilitar espera inicial para entornos de desarrollo
eureka.server.wait-time-in-ms-when-sync-empty=0

# Observabilidad: Actuator + Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
