spring.application.name=empleado-service
server.port=8080


eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# configuraciones de base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/empleado_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:42765715}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE