spring.application.name=solicitudes-service

server.port=${SERVER_PORT:8085}

# Configuración de MongoDB local
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/solicitudes_service}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

#kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
spring.kafka.producer.value-serializer=${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}

# Kafka Consumer (eventos de empleado-service)
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:solicitudes-service-empleado-group}
spring.kafka.consumer.key-deserializer=${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
spring.kafka.consumer.value-deserializer=${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER:org.springframework.kafka.support.serializer.JsonDeserializer}
spring.kafka.consumer.properties.spring.json.trusted.packages=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES:com.sistema.guardias.*,com.jpbravo.*}
spring.kafka.consumer.properties.spring.json.use.type.headers=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_USE_TYPE_HEADERS:false}
spring.kafka.consumer.properties.spring.json.value.default.type=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE:com.jpbravo.solicitudes_service.event.EmpleadoEvent}
# Consumir desde el principio si no hay offset
spring.kafka.consumer.auto-offset-reset=earliest

# Circuit Breaker para Kafka
resilience4j.circuitbreaker.instances.kafkaCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaCB.wait-duration-in-open-state=20s

# Retry para Kafka
resilience4j.retry.instances.kafkaRetry.max-attempts=3
resilience4j.retry.instances.kafkaRetry.wait-duration=2s

# Circuit Breaker para Consumidores Kafka
resilience4j.circuitbreaker.instances.consumerCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.consumerCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.consumerCB.wait-duration-in-open-state=20s

# Retry para Consumidores Kafka
resilience4j.retry.instances.consumerRetry.max-attempts=3
resilience4j.retry.instances.consumerRetry.wait-duration=2s

# Observabilidad: Actuator + Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
